name: Deploy to firebase function on new tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd functions
          npm ci

      - name: Install firebase tools
        run: npm install -g firebase-tools

      - name: Release
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
